### ISSUE TITLE
Add validation for cassandra heap memory params

### ISSUE THREAD

**Issue by Pavinati** [astarte-platform/astarte-kubernetes-operator#107]
Cassandra memory params are passed as is to the envirorment variable `MAX_HEAP_SIZE` which in turn is used for some java CLI command arguments like `-Xms`.

Setting `maxHeapSize` using Mi units leads to a java command error when initializing the cassandra image.

eg:
`maxHeapSize: 2048Mi`

[...]

`Invalid initial heap size: -Xms2048Mi`

It would be nice if the CRD or the operator would validate those fields before the creation of the cassandra deployment

**Comment by matt-mazzucato** [comment]
The Astarte Operator should not handle Cassandra instances. This pattern is deprecated and, as such, not suited for a production deployment.
