### ISSUE TITLE
astarte_data_* queues defaults to just 1 queue  

### ISSUE THREAD

**Issue by bettio** [astarte-platform/astarte-kubernetes-operator#124]
Astarte has multiqueue support for data updater plant, but just a single queue is used.
Queues count should default to 64 instead of 1.

**Comment by matt-mazzucato** [comment]
The issue is addressed by handling the default queue count value in data updater plant within Astarte itself. 
The linked PR is: https://github.com/astarte-platform/astarte/pull/426

**Comment by matt-mazzucato** [comment]
It is reasonable to expose the default on the operator's end. Doing it in #125
