### ISSUE TITLE
Update operator install documentation

### ISSUE THREAD

**Issue by bettio** [astarte-platform/astarte-kubernetes-operator#145]
kubectl -f apply is not enough anymore, update documentation making sure that prereqs are clear (e.g. make, helm, etc...).

**Comment by drf** [comment]
This should migrate to the Helm chart (#147 ) when it's merged

**Comment by matt-mazzucato** [comment]
Closing as the issue is fixed by [this](https://github.com/astarte-platform/astarte/pull/505) PR
