### ISSUE TITLE
Old CFSSL Statefulset doesn't get deleted during the upgrade

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astarte-kubernetes-operator#149]
CFSSL now gets deployed with a Deployment, but during the upgrade the Operator doesn't seems to care about the old Statefulset and it leaves it there hanging. This causes strange problems like, for example, certificates getting signed by the old CFSSL while VerneMQ uses the new one to verify them, leading to all kinds of failures.

**Comment by matt-mazzucato** [comment]
Closed by #204
