### ISSUE TITLE
CFSSL doesn't get restarted if dbConfig is changed

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astarte-kubernetes-operator#162]
If the the database CFSSL is pointing to is changed in the CR, the CFSSL pod should be restarted, otherwise it keeps trying to reach the old database, leading to Pairing failures.

This happens also in the v0.11.x release series, so it must be fixed in release-0.11

**Comment by matt-mazzucato** [comment]
The issue affects only Astarte v0.11.x. Currently, CFSSL is deployed without a database.
Furthermore, starting from Astarte Operator v23.05 the support for Astarte v0.11 will be dropped.
