### ISSUE TITLE
Provide a brand new default ingress to serve requests to Astarte

### ISSUE THREAD

**Issue by matt-mazzucato** [astarte-platform/astarte-kubernetes-operator#229]
Given that Voyager support will be discontinued (see astarte-platform/astarte/issues/613), provide a new default Ingress for Astarte. This new Astarte Ingress has to be a drop-in replacement for the current Astarte Voyager Ingress whose employment will be dropped as of v1.1.

**Comment by isaak42** [comment]
Hi, is there a targeted release date or timeframe for the new Astarte ingress, given that necessary versions of voyager are no longer going to be available on December 31st?

**Comment by matt-mazzucato** [comment]
Hi @isaak42, we are currently in testing phase and the new ingress will be available roughly by the end of the current month.

**Comment by isaak42** [comment]
Thanks, sounds good

**Comment by drf** [comment]
Closed by #247
