### ISSUE TITLE
Example profile for Astarte with external Cassandra

### ISSUE THREAD

**Issue by isaak42** [astarte-platform/astarte-kubernetes-operator#258]
I am attempting to set up an Astarte cluster with an external Cassandra/Scylla database, and am having trouble figuring out which parameters in the CRD need to be specified, and what exactly they all control. Is there anywhere I can find more documentation on the Astarte Cluster CRD? Or an example profile for Astarte with an external database setup? This is potentially related to issue #178. Thanks in advance.

**Comment by matt-mazzucato** [comment]
Hello @isaak42 ,
to configure your external Cassandra you must  set the [`nodes` field](https://github.com/astarte-platform/astarte-kubernetes-operator/blob/release-1.0/apis/api/commontypes/astarte_common_types.go#L304): the string is a list of comma separated `<host>:<port>` of your cassandra nodes. The relevant section should look like this:
```yaml
cassandra:
      deploy: false
      nodes: X.Y.W.Z:9042,A.B.C.D:9042,E.F.G.H:9042
```
If you need to configure your login credentials, then create k8s a login credentials secret (check the [field](https://github.com/astarte-platform/astarte-kubernetes-operator/blob/release-1.0/apis/api/commontypes/astarte_common_types.go#L292) in the crd).
These actions should be sufficient to properly setup your cassandra. If you have any doubts, feel free to ask.

PS: we are currently working to provide a clearer documentation for Astarte CRDs, however I still cannot provide an ETA.

**Comment by isaak42** [comment]
Thanks, that example was helpful and I've got things working now.
