### ISSUE TITLE
Add a default page (404) on ingress which are not configured

### ISSUE THREAD

**Issue by bettio** [astarte-platform/astarte-kubernetes-operator#47]
Following response is returned when visiting a not configured ingress:
```
503 Service Unavailable
No server is available to handle this request.
```

**Comment by matt-mazzucato** [comment]
The AstarteVoyagerIngress is deprecated and will be removed in the next release (i.e. v23.05).
The issue is overcome by the new AstarteDefaultIngress which can properly handle 404 responses.
