### ISSUE TITLE
yaml does not exist 

### ISSUE THREAD

**Issue by shortwavedave** [astarte-platform/astarte-kubernetes-operator#63]
The readme references the following files in the crd folder:

> kubectl apply -f api_v1alpha1_astarte_voyager_ingress_crd.yaml
> kubectl apply -f api_v1alpha1_astarte_crd.yaml
> kubectl get CustomResourceDefinition

These don't exist. What I have are:

> api.astarte-platform.org_astartes_crd.yaml
> api.astarte-platform.org_astartevoyageringresses_crd.yaml
> api.astarte-platform.org_v1alpha1_astarte_cr.yaml
> api.astarte-platform.org_v1alpha1_astartevoyageringress_cr.yaml

but if I try to apply I get an error, e.g.,

```
> kubectl apply -f api.astarte-platform.org_astartes_crd.yaml
The CustomResourceDefinition "astartes.api.astarte-platform.org" is invalid: metadata.annotations: Too long: must have at most 262144 bytes 
```
or

```
> kubectl apply -f api.astarte-platform.org_v1alpha1_astartevoyageringress_cr.yaml
error: unable to recognize "api.astarte-platform.org_v1alpha1_astartevoyageringress_cr.yaml": no matches for kind "AstarteVoyagerIngress" in version "api.astarte-platform.org/v1alpha1"
```

Which files specs should I apply?

**Comment by drf** [comment]
Hi @shortwavedave , the file names have changed between 0.10 and 0.11, and we have just updated the documentation/README. If you want to refer to an Astarte 0.10 installation, you should use files in the release-0.10 branch.

However, I strongly advise you to use astartectl to manage your cluster. Refer to this documentation: https://docs.astarte-platform.org/0.11/030-installation_kubernetes.html
